run:
  timeout: 3m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gofmt
    - misspell
    - unconvert

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
